import type { PassportPageCategory } from './constants'
import { CATEGORY_META } from './constants'
import { parseFields } from './utils'

/**
 * Plain-text field shape used by all formatters. Loosely typed so the
 * formatter can accept either parsed field objects or stringified JSON.
 */
export interface FormatterField {
    key: string
    label: string
    value: string
}

export interface FormatterPage {
    id?: string
    title: string
    category: string
    fields: FormatterField[] | string
}

export interface FormatterOptions {
    /**
     * If true, omit fields whose value is empty or whitespace-only.
     * Defaults to true — empty fields are noise when pasting into a chat.
     */
    skipEmpty?: boolean
    /**
     * If true, prepend a "what is this?" framing sentence so the model
     * treats the block as the user's standing context rather than user
     * input. Useful for tool-specific wrappers (ChatGPT, Claude, etc).
     */
    includeFraming?: boolean
}

/**
 * Coerce a stored `fields` value (stringified JSON or a parsed array) to a
 * normalized array. Delegates to the single shared parser in `lib/utils`
 * so there is one source of truth — and every returned value is guaranteed
 * to be a string, so the formatters never throw on `.trim()`.
 */
function coerceFields(fields: FormatterField[] | string): FormatterField[] {
    return parseFields(fields)
}

/**
 * The plain-text form we ship to the clipboard. Designed to be:
 *  - human-readable when pasted into any chat tool
 *  - easy for a model to parse (clear labels, blank lines between pages)
 *  - short — no marketing boilerplate, no "Generated by Craneta" footer
 *
 * The framing prefix is opt-in because most users won't want it; they
 * usually paste into a "Custom instructions" field that already
 * provides the framing for them.
 */
export function formatPageAsText(
    page: FormatterPage,
    options: FormatterOptions = {}
): string {
    const { skipEmpty = true, includeFraming = false } = options
    const fields = coerceFields(page.fields).filter(
        (f) => !skipEmpty || (typeof f.value === 'string' && f.value.trim())
    )

    const lines: string[] = []
    if (includeFraming) {
        lines.push(
            'The following is structured personal context for the user. Treat it as their standing context for this conversation, not as a question or task.'
        )
        lines.push('')
    }

    lines.push(`## ${page.title.toUpperCase()}`)
    lines.push('')
    for (const field of fields) {
        // Collapse internal newlines so a single field stays as a labeled
        // single line — easier to scan when pasted.
        const value = field.value.replace(/\s+/g, ' ').trim()
        lines.push(`${field.label}: ${value}`)
    }
    lines.push('')
    return lines.join('\n')
}

/**
 * Format multiple pages as a single plain-text block. Pages with no
 * filled fields are skipped entirely (no empty section headers).
 */
export function formatPassportAsText(
    pages: FormatterPage[],
    options: FormatterOptions = {}
): string {
    const { includeFraming = false } = options

    const blocks: string[] = []
    for (const page of pages) {
        const fields = coerceFields(page.fields)
        const hasContent = fields.some(
            (f) => typeof f.value === 'string' && f.value.trim()
        )
        if (!hasContent) continue
        blocks.push(formatPageAsText(page, options))
    }

    if (blocks.length === 0) return ''

    if (includeFraming) {
        const header = [
            'The following is structured personal context for the user, organised by topic.',
            'Each section is a different aspect of how they work, communicate, and what they are focused on.',
            'Treat it as standing context for this and follow-up conversations — not as a question or task.',
            '',
        ]
        return header.concat(blocks).join('\n')
    }
    return blocks.join('\n')
}

/**
 * Build a per-page preview object used by the export page UI to show
 * the user exactly what will be copied. Trims the field list to
 * filled-only and computes a size hint.
 */
export interface PagePreview {
    id: string
    title: string
    category: string
    categoryLabel: string
    filledCount: number
    totalCount: number
    text: string
    charCount: number
    lineCount: number
}

export function buildPagePreview(page: FormatterPage & { id: string }): PagePreview {
    const fields = coerceFields(page.fields)
    const filled = fields.filter(
        (f) => typeof f.value === 'string' && f.value.trim()
    )
    const text = formatPageAsText(page, { skipEmpty: true })
    const categoryMeta =
        CATEGORY_META[page.category as PassportPageCategory] ?? CATEGORY_META.custom

    return {
        id: page.id,
        title: page.title,
        category: page.category,
        categoryLabel: categoryMeta.label,
        filledCount: filled.length,
        totalCount: fields.length,
        text,
        charCount: text.length,
        lineCount: text ? text.split('\n').length : 0,
    }
}

/**
 * Build a per-page preview list, preserving the original order.
 * Pages with no filled content are still included so the user can
 * see them — but their text will be empty.
 */
export function buildPagePreviews(
    pages: Array<FormatterPage & { id: string }>
): PagePreview[] {
    return pages.map(buildPagePreview)
}
